name: Trigger auto deployment for be-nestjs

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/be-nestjs-AutoDeployTrigger-d594a7ab-f800-4097-8f57-db057d4904f6.yml"

  # Allow manual trigger
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  actions: write
  deployments: write
  pages: write
  pull-requests: write
  packages: write

jobs:
  build-and-deploy:
    env:
      HUSKY: 0
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - id: main
        run: pnpm run build

      - if: ${{ steps.main.outcome == 'failure' }}
        run: exit 1

      - name: Prune dev deps, keep only production deps
        run: pnpm prune --prod

      - uses: dopplerhq/cli-action@v3

      - name: Pull secrets from Doppler
        run: doppler secrets download --config prd --no-file --format env > .env
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

      # Make a lowercase owner for GHCR image path (Docker requires lowercase repo names)
      - name: Compute lowercased owner
        id: vars
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.BENESTJS_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.BENESTJS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BENESTJS_REGISTRY_PASSWORD }}
          containerAppName: be-nestjs
          resourceGroup: mma-sdn-project
          imageToBuild: ghcr.io/be-nestjs:${{ github.sha }}
